services:

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-storage:/data
    networks:
      - fastapi-network
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"

  fastapi:
    image: "fastapi-minio:0.1.0"
    container_name: "fastapi-minio"
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - fastapi-network
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    depends_on:
      - minio

volumes:
  minio-storage:

networks:
  fastapi-network:
    driver: bridge
